### ISSUE TITLE
Rig Images on these activities

### ISSUE THREAD

**Issue by ismaeelBM** [cmput301w19t25/3AM-#94]
ViewRBook, OwnerProfileActivty,BorrowerProfileActivity, ViewBook

Note: The function getPageData contains all the code of setting the text and images. So set the images in that function too if possible. If you read it you should be able to get which variable is the user and which is the book.

**Comment by zaheenrahman** [comment]
Okay I'll get started on this soon.

**Comment by zaheenrahman** [comment]
I've written 2 functions in the Branch -ImageRigging. It shows how to load up image into view from the ID.

It's in ViewRBook, called LoadImagefrom..
